export const TRIGGER_LOGGEDIN = 'TRIGGER_LOGGEDIN';
export const TRIGGER_FAILURE = 'TRIGGER_FAILURE';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
