export const TRIGGER_LOGGEDIN = 'TRIGGER_LOGGEDIN';
export const TRIGGER_FAILURE = 'TRIGGER_FAILURE';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';
export const GET_USER_INFO = 'GET_USER_INFO';
export const DELETE_USER_INFO = 'DELETE_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const GET_USER_ENTRIES = 'GET_USER_ENTRIES';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
